### ISSUE TITLE
Убрать фон (100% прозрачность)

### ISSUE THREAD

**Issue by dimanwav** [Danily07/Translumo#10]
Хотелось бы иметь возможность выставить прозрачность фона (цвет окна) на 100%, чтобы его не было вообще, чтобы был только текст )

**Comment by dimanwav** [comment]
И как вариант добавить обводку на текст, я бы сделал белый текст и чрную обводку, разместил бы и мне не мешало бы это прозрачное окно, а так окно приходится закрывать чтобы не мешало, ибо фон не убрать никак...но обводку сделать наверно сложно...

**Comment by Danily07** [comment]
Реализовано в [v0.9.0](https://github.com/Danily07/Translumo/releases/tag/v.0.9.0).
