### ISSUE TITLE
Madworld

### ISSUE THREAD

**Issue by DmitriyPekar** [Danily07/Translumo#11]
![image](https://github.com/Danily07/Translumo/assets/14822106/c0fe8983-e2b8-48b0-9fd1-3c5ec6fa8b36)

в MadWorld'e переводит бывает вот так, это можно пофиксить?

**Comment by Danily07** [comment]
Из того что я увидел, там довольно сложный текст (некий черно-белый cell-shading который сливается с сабами без фона, что создает трудности для распознавания текста). Попробуйте оставить только easyocr в кач-ве движка распознавания. На 100% проблему не решит, но должно стать лучше

**Comment by DmitriyPekar** [comment]
![image](https://github.com/Danily07/Translumo/assets/14822106/079d1af3-9a8c-4ddf-b1c9-bb00230653cd)

вылезает всё равно конечно, жаль что в этой игре так работает

**Comment by Danily07** [comment]
Остается только посоветовать выбирать минимальную область захвата, но все равно, да, полностью в данном случае side-эффекта избежать не удастся.
