### ISSUE TITLE
This applies to "Translumo-master"

### ISSUE THREAD

**Issue by TerrorB1te** [Danily07/Translumo#116]
To Rus.
К сожалению я не разработчик и не понимаю как установить, как мне кажется, более позднюю(публичную) версию(Translumo-master(вер1)).
Является ли "Translumo-master"(по ссылке https://github.com/Danily07/Translumo) экранным переводчиком? если да то я не понимаю как его установить.
"Clone repository (master branch always equals last release version)" это я понял, в Visual Studio 2022(который я предварительно поставил) "фаил">"Clone repository">вставил ссылку>программа загрузила проэкт, но дальше я уже не понял или не нашел в этом разнообразии различных "возможностей", нужнго действия, "Restore packages" не нашел
Пожалуста расскажите по подробнее как установить Translumo-master.
To Eng.
Unfortunately, I’m not a developer and I don’t understand how to install what seems to me to be a later (public) version (Translumo-master (ver1)).
Is "Translumo-master" (at https://github.com/Danily07/Translumo) a screen translator? If so, I don’t understand how to install it.
“Clone repository (master branch always equals last release version)” I understood this, in Visual Studio 2022 (which I previously installed) “file”>”Clone repository”>inserted the link>the program downloaded the project, but I didn’t understand further or I didn’t find in this variety of different “opportunities”, I didn’t find the required action, I didn’t find “Restore packages”.
Please tell more detail how to install Translumo-master.

**Comment by chief876** [comment]
Тебе нужно скачать zip архив и распаковать:
![image](https://github.com/Danily07/Translumo/assets/14109670/52f691c3-66e1-4a1e-9167-ec42e711138a)
![image](https://github.com/Danily07/Translumo/assets/14109670/ce99306f-547a-4b85-9f3e-f1065b2737e7)

Если ты обычный пользователь, то тебе не нужно было устанавливать Visual Studio

**Comment by TerrorB1te** [comment]
Увидел, понял, принял, закрываю.
