### ISSUE TITLE
Can you add "Vietnamese" language to translation language?

### ISSUE THREAD

**Issue by nonamebatbai** [Danily07/Translumo#13]
Can you add "Vietnamese" language to translation language?

**Comment by Danily07** [comment]
Ok, no problems, I'll add it in the next minor update

**Comment by nonamebatbai** [comment]
> Ok, no problems, I'll add it in the next minor update

thank you very much

**Comment by Danily07** [comment]
Added in [0.9.1](https://github.com/Danily07/Translumo/releases/tag/v.0.9.1)

**Comment by groupir96** [comment]
Can you add the Persian (Farsi) language?

**Comment by VAHIDIRAN1** [comment]
Please add Persian language because no game supports this language. Thank you very much
