### ISSUE TITLE
Text detection is failed (TesseractOCREngine)

### ISSUE THREAD

**Issue by Refaire** [Danily07/Translumo#14]
В последней версии не работает, в 0.8.5 на старых библиотеках нормально.
[log20230627.txt](https://github.com/Danily07/Translumo/files/11879288/log20230627.txt)

**Comment by Danily07** [comment]
проверьте, пожалуйста, есть ли в папке models подпапка tessdata?

**Comment by Refaire** [comment]
есть папка tesseract с теми же файлами, что и в tessdata версии 0.8.5

**Comment by Refaire** [comment]
переименование папки в tessdata помогла
