### ISSUE TITLE
Игры на RenPy

### ISSUE THREAD

**Issue by Vladonai** [Danily07/Translumo#15]
Игры на Ренпае могут переводиться только в оконном режиме, потому что окно перевода при активации окна игры (когда оно в фокусе) скрывается. Это неправильно. Функция SetForegroundWindow может быть могла бы помочь. Или опция "принудительный вывод окна перевода впереди всех после каждого нового перевода".

Выбор цвета текста интересный, но чисто белый цвет я установить не смог. Только светло-синий. Нужна более человеческая палитра, может быть простое перечисление - белый, красный, чёрный... Как вариант.

**Comment by Danily07** [comment]
По поводу ограничения работы только в оконном (или безрамочном режиме) было изначально упомянуто в описании. Да, безусловно, доработка до более честного оверлея тоже есть в будущих планах.
Для игр на Renpy можно использовать Borderless Gaming: в игре выставить оконный режим, а затем через программу перевести его в безрамочный.
Не очень, к сожалению, понял поинт про цвет, вот он чисто белый:
![pt](https://github.com/Danily07/Translumo/assets/29047281/337aedf0-1e91-4917-948c-9580c220dd5a)

**Comment by Vladonai** [comment]
Да, мой косяк - изменить цвет на чисто белый можно. Правда у меня программа другую палитру выводит, там ползунком и кружком выбирать цвет надо. Немного неочевидно.

А по Ренпаю - у китайца в Luna Translator окно результатов всегда поверх игры. Там не чистый фулскрин, в Ренпае. Правда еще типы рендеринга разные (GL2 и ANGLE2). А какую программу для перевода игры в безрамочный режим посоветуете?

**Comment by Danily07** [comment]
>  А какую программу для перевода игры в безрамочный режим посоветуете?
Borderless Gaming для большинства вариантов хватает, а там где не работает - fullscreenizer

**Comment by Vladonai** [comment]
Поиграл в игру на Ренпае с Borderless Gaming. Удобно и полноэкранно, но есть проблема: довольно часто программа видимо не определяет, что текст обновился, и перевод не делает. Приходится останавливать и снова запускать распознавание и перевод, дважды нажимая на клавишу с тильдой. Вы какой алгоритм определения изменения содержимого региона используете? Или просто постоянно распознаёте и если результат изменился - отправляете на перевод?

**Comment by Danily07** [comment]
В renpy играх же обычно можно настроить скорость появление текста. Проблема именно в этом (алгоритм в том числе использует объединение фреймов между которыми остается общий текст). С 0.9.0 версией обработка таких случаев должна быть значительно лучше, но временами проблема все же может проскакивать и лучше убирать эту анимацию в настройках (выставлять скорость на максимум).

**Comment by Vladonai** [comment]
Скорость уже на максимуме и весь текст выводится сразу. Но программа не всегда определяет, что текст изменился (во всяком случае мне кажется, что дело именно в этом). Есть ещё вариант, что переводчик отказывает, но я использую Гугл и после остановки и запуска перевода текст определяется и переводится, так что вряд ли дело в этом.

**Comment by Danily07** [comment]
есть ли какие то ошибки в логах? (папка logs)

**Comment by Vladonai** [comment]
Нет, в лог при этом ничего не добавляется.

**Comment by Vladonai** [comment]
Вам удалось воспроизвести у себя эту проблему - то, что не всегда определяется смена текста? Новую версию я скачал - никакой разницы в этом плане.

**Comment by Danily07** [comment]
Непосредственно ваш случай нет, не удалось (я поймал некоторые отдельные редкие пропуски в случаях последовательного текста, это как раз было пофикшено в последней версии).
Очень сильно бы помогло, если б вы на видео записали такой случай, иначе пока не за что зацепиться.

**Comment by Vladonai** [comment]
Заглянул в лог и на этот раз нашёл несколько одинаковых сообщений об ошибках:

19:41:46.681 [ERR] Screen capture failed (code: -2005270489)
Translumo.Processing.Exceptions.CaptureException: Failed to acquire frame
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.CaptureScreen()
   at Translumo.Processing.TranslationProcessingService.TranslateInternal(CancellationToken cancellationToken)

Но вовсе не факт, что они относятся именно к этой проблеме. Потому что иногда проблема есть, а этих сообщений в логе нет.

**Comment by Vladonai** [comment]
Есть какой-нибудь прогресс в решении этой проблемы?

**Comment by Danily07** [comment]
Да, прогресс есть, но много времени сейчас идет на тестирование, т.к. достаточно фундаментальное изменение в механизме

**Comment by Vladonai** [comment]
Это хорошо. Замечу кстати ещё один косяк OCR - путаницу в распознавании букв l и I (маленькая латинская L и большая латинская же i). Нужно ввести правила для этого случая - например словарик таких слов, в которых есть такая путаница.

**Comment by Danily07** [comment]
В [0.9.2](https://github.com/Danily07/Translumo/releases/tag/v.0.9.2) реализовал наконец некоторые улучшения по сравнению текста. Свежий фидбэк по проблеме пропуска строк приветствуется :)

**Comment by Vladonai** [comment]
> В [0.9.2](https://github.com/Danily07/Translumo/releases/tag/v.0.9.2) реализовал наконец некоторые улучшения по сравнению текста. Свежий фидбэк по проблеме пропуска строк приветствуется :)

Протестировал в двух играх в тех местах, где точно были пропуски распознавания. Теперь их нет, так что в первом приближении проблема решена.

Осталось конечно много других проблем - не столько с приложением, сколько собственно с моделями. Как минимум есть проблемы с распознаванием курсива - у WinOCR большая латинская буква i против маленькой буквы L , у Easy OCR двоеточие вместо точки, точка с запятой вместо запятой обычное дело. Может есть модель поновее?

**Comment by Danily07** [comment]
> Протестировал в двух играх в тех местах, где точно были пропуски распознавания. Теперь их нет, так что в первом приближении проблема решена.

супер.
По поводу специфики распознавания: да, есть такое, хотя замена . на ; у Easyocr это наименьшая из проблем :) . Сейчас используются самые новые модели, какого-то простого решения тут нет. На будущее есть планы самостоятельно дообучить EasyOCR модели для повышения точности.
