### ISSUE TITLE
Turkish translation support

### ISSUE THREAD

**Issue by realyasster** [Danily07/Translumo#19]
Hi @Danily07 ,

Almost every translation service supports Turkish. Would you add Turkish translation option?
Thanks.

**Comment by Danily07** [comment]
Hi! Okay, I will add the lang in next updates.

**Comment by OmurD** [comment]
> Hi! Okay, I will add the lang in next updates.
Thank you Danily, we look forward to it! I hope you can bring it soon.

**Comment by EralpNalbant** [comment]
Thank you for bringing Turkish language support, we look forward to it.

**Comment by 777g7g7g** [comment]
> Hi! Okay, I will add the lang in next updates.

Thank you, i really need it

**Comment by Danily07** [comment]
Added in [0.9.2](https://github.com/Danily07/Translumo/releases/tag/v.0.9.2)
