### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by linakima** [Danily07/Translumo#2]
Версия программы 0.8.0
Windows 10 Pro 22H2 19045.3086
Пробовал запускать через права администратора.
Снимал с папки атрибут "только для чтения"
Пробовал в разных режимах совместимости.
Архив с логами прилагаю
[Logs.zip](https://github.com/Danily07/Translumo/files/11779365/Logs.zip)
[DxDiag.txt](https://github.com/Danily07/Translumo/files/11779369/DxDiag.txt)

**Comment by Danily07** [comment]
Попробуйте выставить непосредственно для приложения (translumo.exe) выставить режим высокой производительности в для питания (либо явно установить использование дискретной видеокарты для программы, в зависимости как выглядят эти настройки в панели управления AMD)
Что-то вроде такого https://www.amd.com/en/support/kb/faq/dh-017

**Comment by Rittsuri** [comment]
У меня такая же проблема, просто напросто не запускается
Windows 11 Home 22H2 22621.1702
Пробовал делать тоже самое что и человек выше, но ничего не помогло, даже то что вы писали, возможно это я затупок и сделал все не так как надо, но в общем прилагаю Архив с логами ниже
[log20230617_002.txt](https://github.com/Danily07/Translumo/files/11779704/log20230617_002.txt)
[DxDiag.txt](https://github.com/Danily07/Translumo/files/11779705/DxDiag.txt)

**Comment by linakima** [comment]
Вероятно, что для OCR нужны ядра CUDA, которые есть только на картах Nvidia.
Поэтому и не запускается на машинах с картами AMD.

**Comment by HelLuv** [comment]
@Danily07 возможно полный лог файл поможет чуть больше:
[log20230618.txt](https://github.com/Danily07/Translumo/files/11781741/log20230618.txt)

**Comment by linakima** [comment]
На версии 0.9.0 запустилось!

**Comment by Danily07** [comment]
Исправлено в [v0.9.0](https://github.com/Danily07/Translumo/releases/tag/v.0.9.0).

**Comment by wadim00ss** [comment]
Не запускается на Windows 11
Пробовал все что прописано выше не помогло( 
[log20230902.txt](https://github.com/Danily07/Translumo/files/12503650/log20230902.txt)

**Comment by Danily07** [comment]
@wadim00ss у вас другая ошибка, вот советы по issue #50  попробуйте

**Comment by wadim00ss** [comment]
Спасибо, помогло)
