### ISSUE TITLE
прога перестает переводить

### ISSUE THREAD

**Issue by creempie** [Danily07/Translumo#23]
Распознавание текста в какой-то момент останавливается, и не выдает перевод из области захвата.
То есть, если это диалог, то захват может пропустить реплику. Но при этом, если скипнуть эту реплику, то прога переводит спокойно следующую реплику. То есть программа не выдает критическую ошибку, а просто игнорирует иногда реплики.  
Причем если перезапустить "перевод" через "`", то он тут же захватит реплику и переведет. 

Проблема не большая, нужно просто клацать тильду иногда. Но если это можно исправить, то было бы вообще шикарно. 

ps. тестировал в Якудзе.

**Comment by Danily07** [comment]
Проблема известна, воспроизведена в #15 (там кейс игр на Renpy, но первопричина та же). Закрываю из-за дублирования.
