### ISSUE TITLE
Капча яндекс переводчика пропадает

### ISSUE THREAD

**Issue by Nufahi** [Danily07/Translumo#26]
Часто пользуюсь именно им и возникла такая проблема, что при переводе всплывает окно с просьбой пройти капчу для дальнейшего перевода, но проблема в том, что оно сразу же закрывается и в итоге пройти капчу нереально, что приводит к невозможности использования данного метода перевода. Конечно, я могу перейти на гугл, но вдруг и там попросят капчу и будет тоже самое, в общем, неприятный баг.

**Comment by Danily07** [comment]
у яндекса что-то изменилось в валидации автоматических запросов, буду смотреть. 

> Конечно, я могу перейти на гугл, но вдруг и там попросят капчу и будет тоже самое

нет, нигде больше капчи нет, можете спокойно переходить, но deepl и (возможно) papago могут блокировать по ip через какое-то кол-во времени за интенсивное использование (для избежания этого есть функционал прокси).

**Comment by Danily07** [comment]
Fixed in [0.9.2](https://github.com/Danily07/Translumo/releases/tag/v.0.9.2)

**Comment by giperforg** [comment]
у меня такая же проблема с Яндексом. версия 1.02 стоит, до этого была 0.95 и то же самое
