### ISSUE TITLE
Перевод текста который имеет и русский язык и английский выдает странные слова 

### ISSUE THREAD

**Issue by PabloEskob** [Danily07/Translumo#28]
![Снимок экрана 2023-07-16 001548](https://github.com/Danily07/Translumo/assets/93121681/11f35655-293a-41f6-9ad0-cfd79ced7409)

**Comment by Danily07** [comment]
Текущие доступные движки плохо поддерживают мультиязычность (исключение - латиница, как дополнительный язык. например, перевод с китайского, но встречаются латинские символы. Только такие варианты будут относительно адекватно обрабатываться).
К тому же в вашем случае все равно будет возникать проблема с форматированием текста (левая и правая части будут сливаться). Так что в данном случае могу предложить захватывать только основное окно диалога, а варианты ответа ситуативно переводить через единоразовый перевод (shift + t). В далеких планах есть задача с множественностью областей перевода.
