### ISSUE TITLE
Добавьте, пожалуйста, задержку распознавания текста

### ISSUE THREAD

**Issue by Magnaderra** [Danily07/Translumo#3]
Добавьте, пожалуйста, задержку распознавания текста. Возможно, настраиваемую.

Так получается, что это приложение очень полезно для визуальных новелл и игр с элементами визуальных новелл. А там текст именно появляется постепенно.

Было бы очень здорово установить задержку хотя бы на 3-4 секунды, чтобы переводчик не пытался переводить слова находу сразу же.

Да, я видел, что в ReadMe Вы рекомендовали настраивать одномоментное появление всего текста, но далеко не все игры имеют такую настройку.

**Comment by Danily07** [comment]
Для стандартного случая подхватывания субтитров (в катсценах играх или видео) задержка даже 2-3 секунды будет крайне дискомфортна. 
В качестве компромисса могу вынести в конфигурационный файл этот параметр, чтобы можно было поменять под себя для таких случаев.

**Comment by Magnaderra** [comment]
Это было бы замечательно

**Comment by wterh** [comment]
Полагаю речь шла о ситуациях, когда диалог "печатается", а перевод начинает поступать буквально с первых символов, а так же многократно повторяться по мере появления текста, когда имитируется ввод, а не появляется текст сразу

**Comment by Magnaderra** [comment]
> Полагаю речь шла о ситуациях, когда диалог "печатается", а перевод начинает поступать буквально с первых символов, а так же многократно повторяться по мере появления текста, когда имитируется ввод, а не появляется текст сразу

Да, именно так

**Comment by Danily07** [comment]
Временно реопну issue: хотелось бы получить свежий фидбэк по случаям с последовательным текстом.
Я все же решил не вводить конфигурирования параметра, который бы скорее только вредил, вместо этого несколько 
 переработал и улучшил алгоритм.

**Comment by DezelXI** [comment]
![image](https://github.com/Danily07/Translumo/assets/137102808/43ec29e7-4d16-4518-a89b-e754687d55cc)

К сожалению все же не считывается если текст пишется, переводит только первое слово

**Comment by Danily07** [comment]
спасибо, да, уже понял, что упустил один момент. исправить исправил, но возьму чуть больше времени на тестирование к следующему обновлению.

**Comment by DezelXI** [comment]
> Исправлено в [v0.9.0](https://github.com/Danily07/Translumo/releases/tag/v.0.9.0). Опять же хотелось бы услышать свежий фидбэк

Стало намного лучше, сейчас переводит отлично текст, очень редко какие-то мелкие фразы не переводит, но совсем не критично!

**Comment by TirelEngel** [comment]
> Исправлено в [v0.9.0](https://github.com/Danily07/Translumo/releases/tag/v.0.9.0). Опять же хотелось бы услышать свежий фидбэк

К сожалению на той-же новелле про адвоката работает по старому, если в тексте три строки - будет две неудачные попытки перевести то, что успело напечататься, и третья полноценная.
Т.к. обычно диалоги там двустрочные - получаем переведенное первое слово фразы, а потом всю фразу.
Одинаково на SSD и  HDD

**Comment by wterh** [comment]
Имеет ли смысл предложить идею перевода по хоткею?
Это бы решило проблему лишних запросов и перевода части появляющегося(анимированного) текста, на мой субъективный взгляд.

**Comment by Danily07** [comment]
> > Исправлено в [v0.9.0](https://github.com/Danily07/Translumo/releases/tag/v.0.9.0). Опять же хотелось бы услышать свежий фидбэк
> 
> К сожалению на той-же новелле про адвоката работает по старому, если в тексте три строки - будет две неудачные попытки перевести то, что успело напечататься, и третья полноценная. Т.к. обычно диалоги там двустрочные - получаем переведенное первое слово фразы, а потом всю фразу. Одинаково на SSD и HDD

Если все же напечаталось полностью - я рассматриваю это как удачный результат (т.к. раньше были полные пропуски перевода). А так, безусловно, эти самые "хвосты" будут, когда переводится неполный текст, просто исходя из самой механики распознавая текста в режиме реального времени.

**Comment by Danily07** [comment]
> Имеет ли смысл предложить идею перевода по хоткею? Это бы решило проблему лишних запросов и перевода части появляющегося(анимированного) текста, на мой субъективный взгляд.
перевод по хоткею как раз добавлен в этой версии, только нужно каждый раз выделять область. Вероятно, добавлю в будущих обновлениях, чтобы также одиночно можно было переводить по прошлой области захвата.
А так в принципе пока ничего не мешает в таком виде использовать реал-тайм перевод: сразу включать и выключать его, просто получится два нажатия вместо одного )
