### ISSUE TITLE
Добавление языка

### ISSUE THREAD

**Issue by mikhnyuk** [Danily07/Translumo#30]
Здравствуйте. Не могли бы вы добавить тайский или предоставить пользователю самому добавлять язык? Спасибо

**Comment by mikhnyuk** [comment]
Было бы еще круче если озвучивался переведенный язык

**Comment by Danily07** [comment]
Здравствуйте. Тайский - как язык перевода или определения?
Text to speech также есть в дальнейших планах

**Comment by mikhnyuk** [comment]
> Здравствуйте. Тайский - как язык перевода или определения? Text to speech также есть в дальнейших планах
Определения. 👍
