### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by RogerAllenDu** [Danily07/Translumo#32]
I love this project, everything works well and it's well developed. However the google translate option only returns Russian translation for me, and I don't know why. Is it only with me or it's a bug for everyone?

**Comment by RogerAllenDu** [comment]
I just figured that the  result turns out in Russian only happens when you choose Chinese(Simplified) as the result language. Must be a bug in the settings.

**Comment by mikhnyuk** [comment]
https://github.com/DeskTranslate/DeskTranslate

**Comment by Danily07** [comment]
Fixed in [0.9.2](https://github.com/Danily07/Translumo/releases/tag/v.0.9.2)
