### ISSUE TITLE
add Thai language to translation language please

### ISSUE THREAD

**Issue by pure2103** [Danily07/Translumo#33]
add Thai language to translation language please

**Comment by Danily07** [comment]
Added in [0.9.2](https://github.com/Danily07/Translumo/releases/tag/v.0.9.2)

**Comment by mikhnyuk** [comment]
Возможно ли исходным языком добавить тайский?

**Comment by Danily07** [comment]
Технически возможно, но пока не планируется. Добавление исходных языков довольно трудоемкая доработка, требующая полного цикла обучения модели на языке и дальнейшая подстройка.
