### ISSUE TITLE
капча

### ISSUE THREAD

**Issue by kap0daster** [Danily07/Translumo#38]
открывается окно с капчей но оно пустое

**Comment by Danily07** [comment]
Насколько постоянна проблема? Бывало я тоже ловил его в условном 1 из 10 случаев открытия окна с капчой. 
И это что-то из разряда специфики поведения компонента с встроенным браузером.

**Comment by Danily07** [comment]
На текущий момент яндекс перевод работает относительно стабильно и пустое окно с капчей удается ловить крайне редко. Закрываю issue ввиду отсутствия новых вводных.

**Comment by Dantes017** [comment]
2025, та же проблема постоянно
