### ISSUE TITLE
Курсор наезжает на область с текстом

### ISSUE THREAD

**Issue by Sidiusz** [Danily07/Translumo#41]
Нельзя эту область сделать неактивной? Или отключать, когда в области распознавания нет текста (с задержкой в несколько секунд)

**Comment by Danily07** [comment]
> Нельзя эту область сделать неактивной?
нет, увы. по крайней мере в текущей реализации оверлея. На будущее запланирована задача по отображению другого варианта оверлея "в режиме субтитров", а не целом окне чата. (т.е. имитация строчки субтитров, там наезжать ничего не будет).
Пока могу предложить только вручную через горячие клавиши скрывать окно с переводом.

**Comment by Danily07** [comment]
>  отключать, когда в области распознавания нет текста (с задержкой в несколько секунд)
Немного обдумал и все же запланировал эту фичу, довольно полезная штука была бы. Спасибо за идею.

**Comment by Danily07** [comment]
В [0.9.5](https://github.com/Danily07/Translumo/releases/tag/v.0.9.5) релизе было реализовано отключение кликабельности окна по хоткею и автоматическая очистка окна перевода с заданной задержкой.
