### ISSUE TITLE
Ошибка установки пакета ailed to install language pack

### ISSUE THREAD

**Issue by dimanwav** [Danily07/Translumo#43]
Выбираю исходный язык, японский, корейский, китайский:
- языковой пакет не установлен, хотите установить сейчас?
- ок
- установка языкового пакета
- Ошибка установки пакета ailed to install language pack

Вообщем только английский могу выбрать, с английского переводить на другие языки, а вот азиатские языки не устанавливаются почему то... (у друга норм работает)

Вот что в логах было:
22:23:48.384 [ERR] Language windows pack install error
Translumo.Infrastructure.Exceptions.OptionalFeatureAccessException: Failed to install language pack
 ---> System.Runtime.InteropServices.COMException (0x800F0950): Сбой Add-WindowsCapability. Код ошибки: 0x800f0950
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at Translumo.Infrastructure.Powershell.OptionalFeaturesProvider.OcrLanguagePackInstall(String languageCode)
   at Translumo.Dialog.Stages.StagesFactory.<>c__DisplayClass2_0.<<CreateWindowsOcrCheckingStages>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Translumo.Dialog.Stages.ConditionalInteractionStage.ExecuteInner()
   at Translumo.Dialog.Stages.InteractionStage.ExecuteAsync()

**Comment by Danily07** [comment]
А Windows официальная стоит, не какой то самопальный образ? И не ставили ли случайно всякие твики для системы, которые удаляют "лишние" системные компоненты?
Можете попробовать вручную поставить языковой пакет. Для этого нужно powershell запустить от администратора и ввести:
`> $Capability = Get-WindowsCapability -Online | Where-Object { $_.Name -Like 'Language.OCR*ko-KR*' }
> $Result = $Capability | Add-WindowsCapability -Online` 
это команда для корейского, для других языков соответственно нужно заменить ko-KR на соотв код https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a

**Comment by dimanwav** [comment]
Спасибо, поставил. Образ инсайдерский вин11 канарейка...может какие то твики и были давно, не помню уже х)
