### ISSUE TITLE
Поддержка Linux

### ISSUE THREAD

**Issue by F1N47** [Danily07/Translumo#44]
Привет, автор данного великолепного творения. Есть шансы на появление сборки под Linux-дистрибутивы? Или там все завязано на Windows библиотеки?

**Comment by Danily07** [comment]
День добрый. К сожалению, поддержка кроссплатформенности не планируется, очень многие компоненты завязаны на Windows.

**Comment by GermanAizek** [comment]
> День добрый. К сожалению, поддержка кроссплатформенности не планируется, очень многие компоненты завязаны на Windows.

Ждем порта на Linux, потому что в гитхабе есть много крутых подобных кроссплатформенных переводчиков но хотелось бы что-то от СНГ разработчиков.

**Comment by YogSottot** [comment]
Приложение вполне работает в linux если выбрать tesseract
