### ISSUE TITLE
Текст слишком долго остается на экране

### ISSUE THREAD

**Issue by Taglock** [Danily07/Translumo#49]
Предлагаю добавить в настройки опцию "fade out" с настройкой времени ожидания и затухания.
В моменты когда нет текста на экране, окно перевода висит с текстом и отвлекает.
![image](https://github.com/Danily07/Translumo/assets/39584594/6bea76b0-c369-4957-b2a4-dfe166b80475)

**Comment by Taglock** [comment]
and add options "text alight center" .
sry for my english

**Comment by Danily07** [comment]
День добрый, есть уже похожее предложение, только с полным исчезновением окна #41 
Подумаю, какой вариант из этих лучше реализовать, спасибо. 
Оставлю один issue под вопрос, этот закрою.
