### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by rosenschal** [Danily07/Translumo#5]
Привет!

При клонировании получаю ошибку 

git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.41.0.windows.1

$ git-lfs.exe filter-process
Error downloading object: etc/Models/easyocr.zip (58c5d37): Smudge error: Error downloading etc/Models/easyocr.zip (58c5d3770eaea2792ed976427c904891656e803e74983e013259f2102bb69ce5): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response

**Comment by Danily07** [comment]
Привет!
Как временный workaround:
1) Склонировать репозиторий с игнором компонентов, хранящихся в LFS:
`set GIT_LFS_SKIP_SMUDGE=1  
git clone https://github.com/Danily07/Translumo.git`
2) Скачать репозиторий  как zip архив и скопировать в сколнированный папку etc

**Comment by rosenschal** [comment]
> 

Кажется в таком случае все файлы в etc по 1кб весят
![image](https://github.com/Danily07/Translumo/assets/97950372/49a28989-b6e9-455f-b07b-8439835b245c)

**Comment by Danily07** [comment]
реорганизовал хранение больших компонентов (без хранения внутри самого репозитория), скачиваться будут автоматически при сборке
