### ISSUE TITLE
Ошибка - Требуемый класс отсутствует в ClassFactory

### ISSUE THREAD

**Issue by MLKK1** [Danily07/Translumo#50]
Приветствую!
При первом запуске приложуха запустилась, но не смогла определить OCR. В последующие запуски просто отказывалась отвечать и в логах выдавала ошибку
![image](https://github.com/Danily07/Translumo/assets/140970687/d6abf224-b9d5-4719-8ae7-891159037e46)

**Comment by Danily07** [comment]
Добрый день!
Ошибка возникает из-за системного компонента для Windows OCR, попробуйте следующее:
1) запустить powershell от администратора и выполнить команды:
$Capability = Get-WindowsCapability -Online | Where-Object { $_.Name -Like 'Language.OCR*en-US*' }
и
$Result = $Capability | Remove-WindowsCapability -Online
2) удалить файл сохраненных пользовательских настроек из Users/<Пользователь>/AppData/Roaming/Translumo/settings
3) почистить временные папки 
-> C:\Windows\Temp
-> %USERPROFILE%\AppData\Local\Temp
4) перезапустить ПК и приложение, включить Win OCR
