### ISSUE TITLE
не реалтайм режим

### ISSUE THREAD

**Issue by f242** [Danily07/Translumo#6]
просьба добавить такой режим когда не ведётся постоянного мониторинга, а при необходимости по хоткею выделяется требуемая область и осуществляется её перевод с опцией копирования в буфер, а потом по крестику всё закрывается до следующего раза

**Comment by Danily07** [comment]
Да, такая функциональность в среднесрочных планах есть.
Если что, запланированные фичи и их статус можно посмотреть на [борде](https://trello.com/b/MEHnLySw/translumo).

**Comment by Danily07** [comment]
Реализовано в [v0.9.0](https://github.com/Danily07/Translumo/releases/tag/v.0.9.0).
