### ISSUE TITLE
Проблема с прокси-сервером

### ISSUE THREAD

**Issue by v1rusyak** [Danily07/Translumo#61]
Здравствуйте, спасибо вам за ваше приложение, часто им пользуюсь, но не могли бы вы объяснить как записывать IP адрес состоящий из 2 цифр между точками в вашем приложении?
Пример адреса: 45.95.28.9

**Comment by Danily07** [comment]
Здравствуйте, [вот тут](https://github.com/Danily07/Translumo/issues/40#issuecomment-1699471821) я подсказывал, как вводить прокси
