### ISSUE TITLE
Не ошибка.

### ISSUE THREAD

**Issue by Igrom4ik** [Danily07/Translumo#71]
Супер зачетная программа. Была бы еще возможность транслировать текст там где он находится в игре с наложением по врех существующего текста или ниже. Например GUI инвентаря или характеристик персонажа.

**Comment by Danily07** [comment]
Спасибо! Режим полноценного оверлея, когда он накладывается поверх текста, а также может имитировать полноценные субтитры, есть в долгосрочных планах. Под это предложение уже создавали несколько issue, например, #54. Этот закрою как дубль.
