### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by DziNofu** [Danily07/Translumo#72]
Здравствуйте, встретился с такой вот проблемой, не запускается новая версия(0.9.5), что на HHD, что на SSD где и стоит система. Запускаю от имени администратора, как и положено, но программа лишь на пару секунд появляется в диспетчере задач и исчезает.  Один раз в момент её исчезновением заметил, что статус программа "Не отвечает". При этом прошлая версия(0.9.2) всё ещё исправно работает, что на HHD, что на SSD. В чём проблема не могу понять.

**Comment by Danily07** [comment]
Здравствуйте, 
а как обновлялись на новую версию? Пришлите, пожалуйста, на всякий скрин из папки с exe и последние текстовые логи из папки Logs

**Comment by DziNofu** [comment]
Обновлялся, сперва лишь заменной .exe файла, а потом как раз не запустилось, два раза делал чистую установку на HHD и SSD. Могу сейчас сделать чистую установку версии(0.9.5) и скинуть файл.

**Comment by DziNofu** [comment]
[log20231004.txt](https://github.com/Danily07/Translumo/files/12805565/log20231004.txt)

**Comment by DziNofu** [comment]
В Logs только этот файл

**Comment by Danily07** [comment]
У вас на CTRL+T был переназначен какой-то хоткей?
Вероятно случился конфликт по настройкам, т.к. последнем обновлении добавилась новая горячая клавиша.
Сейчас чтобы исправить проблему вам нужно удалить файл пользовательских настроек  по пути _Users/<Пользователь>/AppData/Roaming/Translumo/settings_ 
В будущем обновлении учту и исправлю баг, спасибо.

**Comment by Danily07** [comment]
После того как файл настроек удалите и таки запустите новую версию можете переназначить как удобно, не проблема)

**Comment by Danily07** [comment]
@DziNofu отпишитесь пжста, если удалось решить проблему с запуском (я закрою issue)

**Comment by DziNofu** [comment]
Да, удаление файла настроек помогло, и всё работает нормально.
