### ISSUE TITLE
Text detection is failed (EasyOCREngine)

### ISSUE THREAD

**Issue by Flaanumans** [Danily07/Translumo#75]
![image](https://github.com/Danily07/Translumo/assets/147530746/464f6edb-bf27-40c7-aff6-cd864b85c3a9)
Windows 10
Видеокарта GTX710
Cuda_12.2.2_537.13
Установка прокси и смена переводчика не помогают, ОЗУ хватает
Tesseract OCR и Windows OCR работают нормально
Пробовал и поставить только EasyOCR, и дополнительно поставить Tesseract OCR и Windows OCR
[log20231010.txt](https://github.com/Danily07/Translumo/files/12859006/log20231010.txt)

**Comment by Danily07** [comment]
Здравствуйте, перепроверил по совместимости с CUDA, увы, GTX 710 все же не поддерживается под необходимую версию PyTorch. 
Обновил системные требования на README странице.
