### ISSUE TITLE
Прекращена работа программы (The program has been terminated)

### ISSUE THREAD

**Issue by HattyPretty** [Danily07/Translumo#76]
Здравствуйте! Вчера всё запускалось, сейчас начало выдавать ошибку. Запускал от имени администратора, переустанавливал разные версии. Ничего не помогает. Так же вчера была проблема с переводом, 1-2 предложения переводил нормально, а потом появлялись иероглифы и знаки, мог не полностью перевести предложение.

Hello! Yesterday everything was running, now it started to give an error. I started it as an administrator, reinstalled different versions. Nothing helps. Also yesterday there was a problem with translation, I translated 1-2 sentences normally, and then hieroglyphs and signs appeared, I could not fully translate the sentence.

[log20231014.txt](https://github.com/Danily07/Translumo/files/12904982/log20231014.txt)

![image](https://github.com/Danily07/Translumo/assets/147921522/3556ad0f-0177-419f-ae5e-f57dbe2a657a)

**Comment by Danily07** [comment]
Здравствуйте!
В #50 была такая же ошибка, попробуйте пройтись по инструкции оттуда, другим пользователям помогло

**Comment by HattyPretty** [comment]
Спасибо, помог этот пункт - 2. Удалить файл сохраненных пользовательских настроек из Users/<Пользователь>/AppData/Roaming/Translumo/settings

Оказалось, что ошибка возникала в случае включения Windows OCR

**Comment by Danily07** [comment]
А если включить обратно теперь win ocr ошибка также повторяется?

**Comment by HattyPretty** [comment]
Да

**Comment by Danily07** [comment]
попробуйте все же первый пункт, только чуть поправил команду, в том issue форматирование символ съело:
`$Capability = Get-WindowsCapability -Online | Where-Object { $_.Name -Like 'Language.OCR*en-US' }`
и
`$Result = $Capability | Remove-WindowsCapability -Online`
(это если англ в качестве исходного языка используется)

**Comment by HattyPretty** [comment]
![image](https://github.com/Danily07/Translumo/assets/147921522/19b065cc-cee9-44b6-8ded-497ce02a2b87)
![image](https://github.com/Danily07/Translumo/assets/147921522/e0bcf837-5222-4c3f-adc4-613d897f906b)

**Comment by Danily07** [comment]
А powershell случайно не с MS store установлен случайно? А то на нем бывают такие проблемы. Если так, то попробуйте грохнуть его и с гитхаба поставить https://github.com/PowerShell/PowerShell/releases/
и еще возьмите команду которую я выше кидал, а не из прошлого issue, там, как я упомянул, она в одном символе неверная

**Comment by HattyPretty** [comment]
Установил версию с гитхаба, команду я брал выше и из прошлого issue ни одна не работает
![image](https://github.com/Danily07/Translumo/assets/147921522/8846f847-7648-4257-80ea-de163557b930)

**Comment by Danily07** [comment]
а какая версия ОС стоит? Можно скрином в таком вот виде
![ws](https://github.com/Danily07/Translumo/assets/29047281/2d572cc4-557b-464c-bf78-4a6e9c35b994)

**Comment by HattyPretty** [comment]
![image](https://github.com/Danily07/Translumo/assets/147921522/16efdf86-c52e-49bf-9cdb-b6c1b4dc5743)

![image](https://github.com/Danily07/Translumo/assets/147921522/daa5bf97-fd89-4ec5-a77b-37a098679208)

**Comment by Danily07** [comment]
М, понятно. Увы, мин. системные требования под поддержку win ocr

> Windows 10 build 19041 (20H1) / Windows 11
