### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by pleasebuyformedaddy** [Danily07/Translumo#8]
![Desktop Screenshot 2023 06 18 - 16 31 21 08](https://github.com/Danily07/Translumo/assets/136971568/ce06ef61-b93a-47b1-9f7e-23cacf8b7076)
я не знаю почему оно так работает, но довольно смешные наборы символов. В любом случае я хз как это исправить

**Comment by DezelXI** [comment]
Мне помогло оставить только эти два,. Автор писал что из-за первого OOC может быть такие проблемы
![image](https://github.com/Danily07/Translumo/assets/137102808/9d78eb5a-ec7a-48a7-8cb7-10eee39c3e4c)

**Comment by pleasebuyformedaddy** [comment]
Огромное спасибо, чел, я уж думал не пройду якудзу

**Comment by pleasebuyformedaddy** [comment]
не знаешь, кстати как убрать дополнительные варианты перевода у deepl?

**Comment by Danily07** [comment]
"похожие" переводы, появляющиеся в чате - это не особенность deepl, а следствия механизм распознавания текста с изображения. На разных фреймах при real-time распознавании движки могут "находить" разный текст (добавлять шумы и делать ошибки), даже если в действительности это еще та же строчка субтитров. 
Алгоритм реализован так, чтобы минимизировать этот эффект, и выдавать повторы, только для "исправления" ошибок предыдущего фрейма, но на 100% этой особенности не избежать.
