### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by DailyFun** [Danily07/Translumo#80]
Иногда бывают моменты что текст сливается с фоном или плохо читабелен, и программа не всегда может внятно подхватить текст
Предлагаю перед тем как выделять необходимую область для перевода выводить окошко с настройками (изменить яркость, контрастность, насыщенность, резкость и т.п.) что бы в реальном времени можно было оценить насколько текст читабелен при определенных настройках.

До твоей шедевра использовал простенькую, но верную программку Maverik OCR Helper. 
Программка хорошо выполняет свою работу, жаль только не переводит в реальном времени. В ней как раз реализовано то о чем я говорю.

**Comment by Danily07** [comment]
Изначально главная задумка приложения была реализовать универсальный переводчик, который способен работать со сложными фонами без дополнительной донастройки со стороны пользователя. Почему мне в целом не нравится с такой ручной настройкой- он банально будет неэффективным. Т.к. если речь идет о переводе в реальном времени текста под видео/игрой, фоном служит динамичное изображение, и настройка препроцессинга для одного фрейма уже будет неэффективна для другого. А там где статичный однотонный фон это банально не нужно - текущая реализация хорошо справляется с этим.
В Maverik Helper и подобном - да, это логичное решение, за счет одиночного захвата текущего изображения.

**Comment by Danily07** [comment]
По итогу: ручной постпроцессинг изображения пока вводить не планируется по причине выше. 
Issue тогда закрою.
