### ISSUE TITLE
Выдает ошибку при установке EasyOCR

### ISSUE THREAD

**Issue by TuesdySprite** [Danily07/Translumo#90]
Несколько раз пыталась скачать и установить версию EasyOCR, но каждый раз после минут двадцати вылетает ошибка.

**Comment by Danily07** [comment]
Попробуйте повторить установку с включенным VPN на компьютере

**Comment by TuesdySprite** [comment]
С VPN он начал выдавать ошибку сразу же.
![n,](https://github.com/Danily07/Translumo/assets/156525965/56dfdfd8-24ee-491d-ad74-c9d39c78b078)

**Comment by TuesdySprite** [comment]
Подождите, а где именно выполнять команды? В самом приложении python?

**Comment by TuesdySprite** [comment]
Я немножко не поняла, что именно мне нужно делать CMD. Потому что если я выбираю подпапку, то он просто её открывает. А если выбираю приложение python, то выходит что-то такое
![image](https://github.com/Danily07/Translumo/assets/156525965/dce0db03-2015-4cff-bb0b-394ece54c4aa)

**Comment by TuesdySprite** [comment]
![image](https://github.com/Danily07/Translumo/assets/156525965/20784102-f602-4c66-8d90-0e51fb66db7e)

**Comment by TuesdySprite** [comment]
![image](https://github.com/Danily07/Translumo/assets/156525965/ce0bd5ff-f57c-4f52-8b3e-796964bcd08d)
После очень долгих манипуляций я у меня получилось, когда я к каждой папке указала адрес

**Comment by TuesdySprite** [comment]
Получилось!
![image](https://github.com/Danily07/Translumo/assets/156525965/ffa096e4-c9ed-498e-ba16-355c3305dd3f)

**Comment by Danily07** [comment]
при первой попытки не нужно было из питона выполнять указанную команду, а из обычного просто CMD перейти сначала в директорию с python :) Но рад, что все получилось в итоге!
