### ISSUE TITLE
Версия для Linux

### ISSUE THREAD

**Issue by Faraon28** [Danily07/Translumo#91]
Имеется ли возможность портировать программу в Linux? Например оформить исходники для ручной сборки или есть возможность упаковать программу в Установщик, что бы поставить её через PlayOnLinux?

**Comment by Danily07** [comment]
Это более реально, чем на Mac (и arm в целом), но все равно есть зависимости, заточенные под windows-only решение.  Через различные надстройки вроде playonlinux и прочих эмуляторов, вероятно, приложение будет работать частично (без easyOCR движка, например). А вот установщик как раз будет к следующей версии.
Полноценное же портирование я рассмотрю в последующих апдейтах, но пока без обещаний и конкретики.
