### ISSUE TITLE
failed easyOCREngine

### ISSUE THREAD

**Issue by Cuphead78** [Danily07/Translumo#97]
![image](https://github.com/Danily07/Translumo/assets/159459813/c37c90f0-7ca6-4f73-a33b-458abe0380e8)
Стала вылезать такая вот ошибка , видеокарта 3060 мобильная

**Comment by Danily07** [comment]
пришлите, пожалуйста, файл текстовых логов из папки log (за соответствующий день)
а какая частота возникновения ошибки? перезапуском не лечится?

**Comment by Cuphead78** [comment]
[log20240208.txt](https://github.com/Danily07/Translumo/files/14214892/log20240208.txt)
Перезапуском не лечится (

**Comment by Danily07** [comment]
Похоже, что одна из python'овских библиотек получила обновление и теперь конфликтует с текущей версией easyOCR - можете пока использовать решение [отсюда
](https://github.com/Danily07/Translumo/issues/96#issuecomment-1925366846)
Постараюсь в ближайшее время выпустить хотфикс с более удобным решением проблемы

**Comment by Danily07** [comment]
Fixed in [0.9.6](https://github.com/Danily07/Translumo/releases/tag/v.0.9.6)
