### ISSUE TITLE
Text detection is failed (EasyOCREngine)

### ISSUE THREAD

**Issue by Qwoorr** [Danily07/Translumo#98]
Собственно, ошибка - в названии. Прикрепляю лог. Заранее спасибо.
[log20240209.txt](https://github.com/Danily07/Translumo/files/14217519/log20240209.txt)

**Comment by Danily07** [comment]
Похоже, что одна из python'овских библиотек получила обновление и теперь конфликтует с текущей версией easyOCR - можете использовать решение [отсюда](https://github.com/Danily07/Translumo/issues/96#issuecomment-1925366846)
Этот issue закрою как дубль, #97 оставлю под проблему - постараюсь в ближайшее время выпустить хотфикс с более удобным решением проблемы

**Comment by Qwoorr** [comment]
Не помогло.

**Comment by Danily07** [comment]
Сори за задержку, выпустил хотфикс в новой версии [0.9.6](https://github.com/Danily07/Translumo/releases/tag/v.0.9.6)
